package com.love.converter.string.processor.model;

public enum Action {
    SPLIT, REMOVE, FILTER, STARTS_WITH, NOT_STARTS_WITH, ENDS_WITH, NOT_ENDS_WITH, CONTAINS, NOT_CONTAINS, MERGE,
    SPLIT_GET_HEAD, SPLIT_GET_TAIL, LOWERCASE, UPPERCASE
}
